"""Engram Python SDK - SDK for Engram Memory Server."""
import logging

__version__ = "1.0.0"

# Library best practice: attach NullHandler so consumers who don't configure
# logging never see "No handler found" warnings.  Users can still attach their
# own handlers to the "engram" logger to observe SDK behaviour.
logging.getLogger("engram").addHandler(logging.NullHandler())

# Client classes
from engram.client import (
    AsyncEngramClient,
    EngramClient,
    create_async_engram_client,
    create_engram_client,
)

# Error hierarchy
from engram.errors import (
    EngramError,
    EngramTimeoutError,
    InternalError,
    NetworkError,
    NotFoundError,
    SessionExistsError,
    UnauthorizedError,
    ValidationError,
    parse_api_error,
)

# Resource classes
from engram.resources import (
    AuditResource,
    BlobsResource,
    CrystalHierarchyResource,
    CrystalItemsResource,
    CrystalsResource,
    CrystalVersionsResource,
    EdgesResource,
    ExportImportResource,
    NotesResource,
    SessionBranchesResource,
    SessionConstraintsResource,
    SessionDecisionPointsResource,
    SessionLinksResource,
    SessionNoteEdgesResource,
    SessionNotesResource,
    SessionScratchResource,
    SessionsResource,
    SessionStuckDetectionsResource,
    SyncAuditResource,
    SyncBlobsResource,
    SyncCrystalHierarchyResource,
    SyncCrystalItemsResource,
    SyncCrystalsResource,
    SyncCrystalVersionsResource,
    SyncEdgesResource,
    SyncExportImportResource,
    SyncNotesResource,
    SyncSessionBranchesResource,
    SyncSessionConstraintsResource,
    SyncSessionDecisionPointsResource,
    SyncSessionLinksResource,
    SyncSessionNoteEdgesResource,
    SyncSessionNotesResource,
    SyncSessionScratchResource,
    SyncSessionsResource,
    SyncSessionStuckDetectionsResource,
    TerrafirmaResource,
    SyncTerrafirmaResource,
    EntitiesResource,
    SyncEntitiesResource,
    EventsResource,
    SyncEventsResource,
    EventSubscription,
    ExtractionResource,
    SyncExtractionResource,
)

# Types (re-exported from types subpackage — explicit imports)
from engram.types.common import (
    ApiResponse,
    PaginatedResult,
    PaginationMeta,
)
from engram.types.sessions import (
    CreateLocalNoteParams,
    CreateLocalSessionParams,
    CreateScratchParams,
    FinalizeSessionOptions,
    FinalizeSessionResult,
    LifecycleStats,
    LifecycleStatus,
    ListLocalNotesParams,
    ListLocalSessionsParams,
    ListScratchParams,
    LocalSearchResult,
    LocalSession,
    LocalSessionNote,
    NoteEmbeddingStatus,
    SearchLocalNotesParams,
    SessionScratch,
    UpdateLifecycleParams,
    UpdateLocalNoteParams,
    UpdateLocalSessionParams,
    UpdateScratchParams,
)
from engram.types.knowledge_crystal import (
    AddChildCrystalParams,
    AddCrystalItemParams,
    ContainedCrystal,
    ContentNodeType,
    ContentRef,
    CreateCrystalVersionParams,
    CreateKnowledgeCrystalEdgeParams,
    CreateKnowledgeCrystalParams,
    CreateVersionParams,
    CrystalHierarchy,
    CrystalItem,
    CrystalMembership,
    CrystalVersion,
    EmbeddingStatus,
    GetRelatedParams,
    KnowledgeCrystal,
    KnowledgeCrystalEdge,
    KnowledgeCrystalEdgeRelationship,
    KnowledgeCrystalSearchResult,
    ListCrystalItemsParams,
    ListCrystalVersionsParams,
    ListHierarchyParams,
    ListKnowledgeCrystalEdgesParams,
    ListKnowledgeCrystalsParams,
    MembershipAddedBy,
    NodeType,
    NodeVisibility,
    ParentCrystal,
    PromoteParams,
    PromoteResult,
    PromotionSummary,
    ScopedSearchParams,
    ScopedSearchResult,
    SearchKnowledgeCrystalsParams,
    SourceType,
    UpdateKnowledgeCrystalEdgeParams,
    UpdateKnowledgeCrystalParams,
)
from engram.types.crystals import (
    AclEntry,
    BulkAddParams,
    CreateShareLinkParams,
    CrystalPermission,
    ForkCrystalParams,
    GranteeType,
    GrantPermissionParams,
    ReorderParams,
    RevokePermissionParams,
    ShareLink,
    SharedCrystalResult,
)
from engram.types.coordination import (
    BranchTreeNode,
    BranchTreeNodeBranch,
    CloseBranchParams,
    ConstraintViolation,
    CreateBranchParams,
    CreateConstraintParams,
    CreateDecisionPointParams,
    CreateNoteEdgeParams,
    CreateSessionLinkParams,
    CreateStuckDetectionParams,
    DecisionPoint,
    DecisionPointWithBranches,
    ExplorationBranch,
    ListBranchesParams,
    ListConstraintsParams,
    ListDecisionPointsParams,
    ListNoteEdgesParams,
    ListSessionLinksParams,
    ListStuckDetectionsParams,
    NoteTraversalResult,
    ResolveStuckDetectionParams,
    SessionConstraint,
    SessionLink,
    SessionNoteEdge,
    StuckDetection,
    TraverseNotesParams,
    UpdateBranchParams,
    UpdateConstraintParams,
    UpdateDecisionPointParams,
)
from engram.types.terrafirma import (
    CrystalMembershipInfo,
    FileConflictInfo,
    MigrationCurrentStatus,
    MigrationError,
    MigrationStartResult,
    MigrationStatus,
    ProcessStatus,
    StartMigrationOptions,
    SyncResult,
    SyncScope,
    SyncStatus,
    TerrafirmaFileInfo,
    TerrafirmaMode,
    TerrafirmaReconcilerStatus,
    TerrafirmaStatus,
    TerrafirmaSuggestedAction,
    TerrafirmaSyncCounts,
    TerrafirmaWatcherStatus,
    TriggerSyncOptions,
)
from engram.types.embeddings import (
    BatchEmbeddingResponse,
    EmbeddingInfoResponse,
    EmbeddingModule,
    EmbeddingRequest,
    EmbeddingResponse,
)
from engram.types.blobs import (
    BlobMetadata,
    BlobReference,
    BlobUploadResponse,
    GcResult,
)
from engram.types.audit import (
    AuditBatchIngestParams,
    AuditBatchIngestResult,
    AuditEvent,
    AuditEventType,
    AuditFlushResult,
    AuditIngestParams,
    AuditIngestResult,
    AuditIngesterStats,
    AuditListParams,
    AuditOutcome,
    AuditPruneParams,
    AuditPruneResult,
    AuditStats,
    AuditStatsParams,
    LogLevel,
)
from engram.types.export_import import (
    ConflictResolution,
    ExportEstimate,
    ExportFilter,
    ExportFormat,
    ExportParams,
    ExportScope,
    ImportConflict,
    ImportOptions,
    ImportPreview,
    ImportPreviewCounts,
    ImportPreviewError,
    ImportPreviewSchemaVersion,
    ImportResult,
    ImportResultCounts,
    ImportResultError,
)

from engram.types.events import (
    EngramEventType,
    EngramStreamEvent,
)

from engram.types.entities import (
    EntityCard,
    EntityClass,
    EntityEdge,
    EntityMention,
    EntityRelationship,
    EntityReviewAction,
    EntityReviewResult,
    EntityWithEdges,
    ExtractionConfig,
    ExtractionJob,
    ExtractionJobStatus,
    ExtractionStats,
)

import warnings as _warnings


def __getattr__(name: str) -> type:
    """Lazy attribute lookup — provides deprecated ``TimeoutError`` alias."""
    if name == "TimeoutError":
        _warnings.warn(
            "engram.TimeoutError is deprecated and shadows the Python "
            "builtin. Use engram.EngramTimeoutError instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return EngramTimeoutError
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

__all__ = [
    "__version__",
    # Client
    "AsyncEngramClient",
    "EngramClient",
    "create_async_engram_client",
    "create_engram_client",
    # Errors
    "EngramError",
    "EngramTimeoutError",
    "InternalError",
    "NetworkError",
    "NotFoundError",
    "SessionExistsError",
    "TimeoutError",  # Deprecated alias for EngramTimeoutError
    "UnauthorizedError",
    "ValidationError",
    "parse_api_error",
    # Resource classes
    "AuditResource",
    "SyncAuditResource",
    "BlobsResource",
    "SyncBlobsResource",
    "CrystalHierarchyResource",
    "SyncCrystalHierarchyResource",
    "CrystalItemsResource",
    "SyncCrystalItemsResource",
    "CrystalsResource",
    "SyncCrystalsResource",
    "CrystalVersionsResource",
    "SyncCrystalVersionsResource",
    "EdgesResource",
    "SyncEdgesResource",
    "ExportImportResource",
    "SyncExportImportResource",
    "NotesResource",
    "SyncNotesResource",
    "SessionBranchesResource",
    "SyncSessionBranchesResource",
    "SessionConstraintsResource",
    "SyncSessionConstraintsResource",
    "SessionDecisionPointsResource",
    "SyncSessionDecisionPointsResource",
    "SessionLinksResource",
    "SyncSessionLinksResource",
    "SessionNoteEdgesResource",
    "SyncSessionNoteEdgesResource",
    "SessionNotesResource",
    "SyncSessionNotesResource",
    "SessionScratchResource",
    "SyncSessionScratchResource",
    "SessionsResource",
    "SyncSessionsResource",
    "SessionStuckDetectionsResource",
    "SyncSessionStuckDetectionsResource",
    "TerrafirmaResource",
    "SyncTerrafirmaResource",
    "EntitiesResource",
    "SyncEntitiesResource",
    "EventsResource",
    "SyncEventsResource",
    "EventSubscription",
    "ExtractionResource",
    "SyncExtractionResource",
    # Common types
    "PaginatedResult",
    "PaginationMeta",
    "ApiResponse",
    # Session types
    "LocalSession",
    "LocalSessionNote",
    "LocalSearchResult",
    "SessionScratch",
    "FinalizeSessionResult",
    "NoteEmbeddingStatus",
    "LifecycleStatus",
    "UpdateLifecycleParams",
    "LifecycleStats",
    "CreateLocalSessionParams",
    "UpdateLocalSessionParams",
    "ListLocalSessionsParams",
    "CreateLocalNoteParams",
    "UpdateLocalNoteParams",
    "ListLocalNotesParams",
    "SearchLocalNotesParams",
    "CreateScratchParams",
    "UpdateScratchParams",
    "ListScratchParams",
    "FinalizeSessionOptions",
    # Knowledge Crystal types (unified)
    "NodeType",
    "NodeVisibility",
    "EmbeddingStatus",
    "MembershipAddedBy",
    "KnowledgeCrystalEdgeRelationship",
    "SourceType",
    "ContentNodeType",
    "ContentRef",
    "KnowledgeCrystal",
    "KnowledgeCrystalSearchResult",
    "KnowledgeCrystalEdge",
    "CreateKnowledgeCrystalParams",
    "UpdateKnowledgeCrystalParams",
    "ListKnowledgeCrystalsParams",
    "SearchKnowledgeCrystalsParams",
    "CreateKnowledgeCrystalEdgeParams",
    "UpdateKnowledgeCrystalEdgeParams",
    "ListKnowledgeCrystalEdgesParams",
    "CrystalMembership",
    "CrystalItem",
    "CrystalVersion",
    "AddCrystalItemParams",
    "ListCrystalItemsParams",
    "CreateCrystalVersionParams",
    "ListCrystalVersionsParams",
    "ContainedCrystal",
    "ParentCrystal",
    "CrystalHierarchy",
    "ScopedSearchResult",
    "AddChildCrystalParams",
    "ListHierarchyParams",
    "ScopedSearchParams",
    "PromoteParams",
    "PromoteResult",
    "PromotionSummary",
    "CreateVersionParams",
    "GetRelatedParams",
    # Crystal ACL/sharing types
    "CrystalPermission",
    "GranteeType",
    "AclEntry",
    "ShareLink",
    "SharedCrystalResult",
    "BulkAddParams",
    "ReorderParams",
    "GrantPermissionParams",
    "RevokePermissionParams",
    "CreateShareLinkParams",
    "ForkCrystalParams",
    # Coordination types
    "SessionConstraint",
    "ConstraintViolation",
    "DecisionPoint",
    "DecisionPointWithBranches",
    "ExplorationBranch",
    "BranchTreeNodeBranch",
    "BranchTreeNode",
    "SessionNoteEdge",
    "NoteTraversalResult",
    "StuckDetection",
    "SessionLink",
    "CreateConstraintParams",
    "UpdateConstraintParams",
    "ListConstraintsParams",
    "CreateDecisionPointParams",
    "UpdateDecisionPointParams",
    "ListDecisionPointsParams",
    "CreateBranchParams",
    "UpdateBranchParams",
    "CloseBranchParams",
    "ListBranchesParams",
    "CreateNoteEdgeParams",
    "ListNoteEdgesParams",
    "TraverseNotesParams",
    "CreateStuckDetectionParams",
    "ResolveStuckDetectionParams",
    "ListStuckDetectionsParams",
    "CreateSessionLinkParams",
    "ListSessionLinksParams",
    # Terrafirma types
    "TerrafirmaMode",
    "ProcessStatus",
    "SyncStatus",
    "MigrationStatus",
    "SyncScope",
    "TerrafirmaWatcherStatus",
    "TerrafirmaReconcilerStatus",
    "TerrafirmaSyncCounts",
    "TerrafirmaSuggestedAction",
    "TerrafirmaStatus",
    "CrystalMembershipInfo",
    "FileConflictInfo",
    "TerrafirmaFileInfo",
    "MigrationStartResult",
    "MigrationError",
    "MigrationCurrentStatus",
    "SyncResult",
    "StartMigrationOptions",
    "TriggerSyncOptions",
    # Embedding types
    "EmbeddingModule",
    "EmbeddingRequest",
    "EmbeddingResponse",
    "BatchEmbeddingResponse",
    "EmbeddingInfoResponse",
    # Blob types
    "BlobMetadata",
    "BlobUploadResponse",
    "BlobReference",
    "GcResult",
    # Audit types
    "LogLevel",
    "AuditEventType",
    "AuditOutcome",
    "AuditEvent",
    "AuditIngestResult",
    "AuditBatchIngestResult",
    "AuditFlushResult",
    "AuditStats",
    "AuditIngesterStats",
    "AuditPruneResult",
    "AuditIngestParams",
    "AuditBatchIngestParams",
    "AuditListParams",
    "AuditStatsParams",
    "AuditPruneParams",
    # Export/Import types
    "ExportScope",
    "ExportFormat",
    "ConflictResolution",
    "ExportFilter",
    "ExportParams",
    "ImportOptions",
    "ExportEstimate",
    "ImportConflict",
    "ImportPreview",
    "ImportPreviewSchemaVersion",
    "ImportPreviewCounts",
    "ImportPreviewError",
    "ImportResult",
    "ImportResultError",
    "ImportResultCounts",
    # Event types (SSE streaming)
    "EngramEventType",
    "EngramStreamEvent",
    # Entity types
    "EntityClass",
    "EntityReviewAction",
    "ExtractionJobStatus",
    "EntityCard",
    "EntityEdge",
    "EntityWithEdges",
    "EntityMention",
    "EntityRelationship",
    "EntityReviewResult",
    # Extraction types
    "ExtractionJob",
    "ExtractionConfig",
    "ExtractionStats",
]
