TOOLKIT := scripts/release-toolkit/lib
SUMMARY := . $(TOOLKIT)/common.sh && . $(TOOLKIT)/summary.sh

.DEFAULT_GOAL := help

.PHONY: help install ensure-deps build lint test check clean publish claudemd-check

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'

install: ## Install dependencies
	@$(SUMMARY) && run_summarized generic "pnpm install --frozen-lockfile" .logs/install.log

NODE_MODULES := node_modules/.package-lock.json

$(NODE_MODULES): package.json pnpm-lock.yaml
	@$(SUMMARY) && run_summarized generic "pnpm install --frozen-lockfile" .logs/install.log
	@touch $@

ensure-deps: $(NODE_MODULES) ## Install deps if missing (fast no-op otherwise)

build: ensure-deps ## Build all packages
	@$(SUMMARY) && run_summarized tsc "pnpm run build" .logs/build.log

lint: ensure-deps ## Lint and typecheck
	@$(SUMMARY) && run_summarized tsc "pnpm run lint" .logs/lint.log

test: ensure-deps ## Run tests
	@$(SUMMARY) && run_summarized vitest "pnpm run test" .logs/test.log

# Fingerprint of the exact tree state (HEAD + staged/unstaged changes).
# `check` records it; `publish` refuses to run unless the recorded
# fingerprint matches the current tree, so nothing reaches npm without
# lint+test having passed against the exact code being published —
# even if someone tries to skip the prerequisite (e.g. `make -o check`).
CHECK_STAMP := .logs/.check-stamp
TREE_FINGERPRINT := { git rev-parse HEAD; git status --porcelain; git diff HEAD; } | git hash-object --stdin

check: lint test claudemd-check ## Run full CI gate (lint + test + docs drift)
	@mkdir -p .logs && $(TREE_FINGERPRINT) > $(CHECK_STAMP)

clean: ## Remove build artifacts
	@rm -rf .logs
	pnpm run clean

publish: build check ## Publish to npm via changesets (hard-gated on check)
	@# Releases happen from a clean, pushed main only (RELEASING.md
	@# pre-publish checklist — enforced here, not just documented).
	@# Both guards run BEFORE `changeset version` mutates anything.
	@# No --quiet: network errors during the critical publish fetch must
	@# be visible (a silent fetch failure could let a stale on-main check
	@# pass).
	@git fetch origin main
	@if [ -n "$$(git status --porcelain)" ]; then \
		echo "❌ Working tree is not clean. Refusing to publish."; \
		exit 1; \
	fi
	@if [ "$$(git rev-parse HEAD)" != "$$(git rev-parse origin/main)" ]; then \
		echo "❌ HEAD is not origin/main. Refusing to publish."; \
		exit 1; \
	fi
	@current="$$($(TREE_FINGERPRINT))"; stamp="$$(cat $(CHECK_STAMP) 2>/dev/null)"; \
	if [ -z "$$stamp" ] || [ "$$current" != "$$stamp" ]; then \
		echo "❌ 'make check' has not passed against this exact tree. Refusing to publish."; \
		exit 1; \
	fi
ifeq ($(DRY_RUN),1)
	@# Recipe lines run in separate shells, so a plain `exit 0` here
	@# would only end its own line and the recipe would keep going —
	@# the stop must be a make-level conditional.
	@echo "✅ DRY_RUN=1: all pre-publish gates passed; stopping before version bump and npm."
else
	@npm whoami >/dev/null 2>&1 || (echo "❌ Not logged in to npm. Run 'npm login' first." && exit 1)
	pnpm run version-packages
	git add -A
	@# Only commit when the version flow actually produced changes.
	@# When every pending changeset has already been consumed (e.g. the
	@# version bump landed in a prior feature PR), the working tree stays
	@# clean after `changeset version` and a plain `git commit` would
	@# fail with exit 1 — aborting publish+tag-push. Skip the commit in
	@# that case so `changeset publish` still runs.
	git diff --cached --quiet || git commit -m "chore: version packages"
	@# Re-run the FULL gate against the post-bump tree, live, in this
	@# same invocation. `changeset version` mutates package.json versions
	@# (and version-packages syncs CLAUDE.md); the pre-bump check above
	@# never saw that tree. The 2.0.0/0.7.0 release proved the gap: check
	@# passed pre-bump, the bump created CLAUDE.md drift, and main landed
	@# red. A pre-stamped fingerprint cannot satisfy this step — it is a
	@# fresh run.
	$(MAKE) check
	@# Provenance is EXPLICITLY declined: npm provenance attestation
	@# requires a supported CI OIDC provider (GitHub Actions / GitLab CI)
	@# and cannot be generated by a local publish. The Actions release
	@# workflow that set NPM_CONFIG_PROVENANCE=true was archived in
	@# cef5ad7 (see docs/archive/2026-03-29-github-actions-release.yml).
	@# DEFERRED: restore attestation when a CI publisher returns.
	@# See RELEASING.md "Provenance" for details.
	NPM_CONFIG_PROVENANCE=false pnpm changeset publish
	git push origin main --tags
endif

claudemd-check: ## Check CLAUDE.md package table matches actual versions
	@./scripts/check-claudemd-versions.sh

# Changelog
# 2026-04-04  Add build summary (run_summarized via release-toolkit)
# 2026-04-14  Make `publish` target idempotent on already-versioned state
# 2026-04-15  Add claudemd-check target + RELEASING.md
# 2026-04-16  Add npm auth preflight check to `publish` target
# 2026-04-20  Add ensure-deps sentinel (workspace convention)
# 2026-06-11  Wire claudemd-check into `check`; script also guards resource count
# 2026-06-11  Hard-gate publish on check via tree fingerprint stamp;
#             explicitly decline npm provenance (NPM_CONFIG_PROVENANCE=false)
#             for local publishes — unsupported without a CI OIDC provider
# 2026-06-12  Close the 2.0.0 release-gate gap (next-stage Initiative 1):
#             publish refuses on dirty tree / HEAD != origin/main, version
#             flow syncs CLAUDE.md (pnpm run version-packages), full check
#             re-runs live against the post-bump tree, DRY_RUN=1 stops
#             before version bump and npm for gate testing
