TOOLKIT := scripts/release-toolkit/lib
SUMMARY := . $(TOOLKIT)/common.sh && . $(TOOLKIT)/summary.sh

.DEFAULT_GOAL := help

.PHONY: help install ensure-deps build lint test python-test check clean publish claudemd-check

help: ## Show available targets
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-15s\033[0m %s\n", $$1, $$2}'

install: ## Install dependencies
	@$(SUMMARY) && run_summarized generic "pnpm install --frozen-lockfile" .logs/install.log

NODE_MODULES := node_modules/.package-lock.json

$(NODE_MODULES): package.json pnpm-lock.yaml
	@$(SUMMARY) && run_summarized generic "pnpm install --frozen-lockfile" .logs/install.log
	@touch $@

ensure-deps: $(NODE_MODULES) ## Install deps if missing (fast no-op otherwise)

build: ensure-deps ## Build all packages
	@$(SUMMARY) && run_summarized tsc "pnpm run build" .logs/build.log

lint: ensure-deps ## Lint and typecheck
	@$(SUMMARY) && run_summarized tsc "pnpm run lint" .logs/lint.log

test: ensure-deps ## Run tests
	@$(SUMMARY) && run_summarized vitest "pnpm run test" .logs/test.log

# Fingerprint of the exact tree state (HEAD + staged/unstaged changes).
# `check` records it; `publish` refuses to run unless the recorded
# fingerprint matches the current tree, so nothing reaches npm without
# lint+test having passed against the exact code being published —
# even if someone tries to skip the prerequisite (e.g. `make -o check`).
CHECK_STAMP := .logs/.check-stamp
TREE_FINGERPRINT := { git rev-parse HEAD; git status --porcelain; git diff HEAD; } | git hash-object --stdin

python-test: ## Run the sdk-python core unit suite (mocked transport)
	@$(SUMMARY) && run_summarized generic "./scripts/run-python-tests.sh" .logs/python-test.log

check: lint test python-test claudemd-check ## Run full CI gate (lint + test + python + docs drift)
	@mkdir -p .logs && $(TREE_FINGERPRINT) > $(CHECK_STAMP)

clean: ## Remove build artifacts
	@rm -rf .logs
	pnpm run clean

publish: build check ## Publish to npm via changesets (hard-gated on check)
	@current="$$($(TREE_FINGERPRINT))"; stamp="$$(cat $(CHECK_STAMP) 2>/dev/null)"; \
	if [ -z "$$stamp" ] || [ "$$current" != "$$stamp" ]; then \
		echo "❌ 'make check' has not passed against this exact tree. Refusing to publish."; \
		exit 1; \
	fi
	@npm whoami >/dev/null 2>&1 || (echo "❌ Not logged in to npm. Run 'npm login' first." && exit 1)
	pnpm changeset version
	git add -A
	@# Only commit when `changeset version` actually produced changes.
	@# When every pending changeset has already been consumed (e.g. the
	@# version bump landed in a prior feature PR), the working tree stays
	@# clean after `changeset version` and a plain `git commit` would
	@# fail with exit 1 — aborting publish+tag-push. Skip the commit in
	@# that case so `changeset publish` still runs.
	git diff --cached --quiet || git commit -m "chore: version packages"
	@# Provenance is EXPLICITLY declined: npm provenance attestation
	@# requires a supported CI OIDC provider (GitHub Actions / GitLab CI)
	@# and cannot be generated by a local publish. The Actions release
	@# workflow that set NPM_CONFIG_PROVENANCE=true was archived in
	@# cef5ad7 (see docs/archive/2026-03-29-github-actions-release.yml).
	@# DEFERRED: restore attestation when a CI publisher returns.
	@# See RELEASING.md "Provenance" for details.
	NPM_CONFIG_PROVENANCE=false pnpm changeset publish
	git push origin main --tags

claudemd-check: ## Check CLAUDE.md package table matches actual versions
	@./scripts/check-claudemd-versions.sh

# Changelog
# 2026-04-04  Add build summary (run_summarized via release-toolkit)
# 2026-04-14  Make `publish` target idempotent on already-versioned state
# 2026-04-15  Add claudemd-check target + RELEASING.md
# 2026-04-16  Add npm auth preflight check to `publish` target
# 2026-04-20  Add ensure-deps sentinel (workspace convention)
# 2026-06-11  Wire claudemd-check into `check`; script also guards resource count
# 2026-06-11  Hard-gate publish on check via tree fingerprint stamp;
#             explicitly decline npm provenance (NPM_CONFIG_PROVENANCE=false)
#             for local publishes — unsupported without a CI OIDC provider
# 2026-06-12  Add python-test (sdk-python pytest via scripts/run-python-tests.sh)
#             and wire it into `check` (next-stage Initiative 3, Phase B). Only
#             the .PHONY + check + new python-test lines were touched, to keep
#             the merge with the in-flight publish-target restructure (PR #87)
#             trivial.
